---
abstract: 'Gearman workers launcher with register functions'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  File::Which: 0
  Gearman::Client: 0
  Net::EmptyPort: 0
  Test::More: 0.98
  Test::TCP: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-Starter
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Gearman::Starter:
    file: lib/Gearman/Starter.pm
    version: 0.02
  Gearman::Starter::Util:
    file: lib/Gearman/Starter/Util.pm
requires:
  Class::Accessor::Lite: 0
  Class::Inspector: 0
  Filesys::Notify::Simple: 0
  Gearman::Worker: 0
  Getopt::Long: 0
  Hash::Rename: 0
  Module::Load: 0
  Parallel::Prefork: 0
  Parallel::Scoreboard: 0
  Pod::Usage: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/gearman-starter.pl/issues
  homepage: https://github.com/tokuhirom/gearman-starter.pl
  repository: git://github.com/tokuhirom/gearman-starter.pl.git
version: 0.02
x_contributors:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Songmu <y.songmu@gmail.com>'
